# Generated by Django 4.2.7 on 2023-12-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
            ],
        ),
    ]
