# Generated by Django 4.2.7 on 2023-12-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='verset',
            field=models.CharField(default='', max_length=5000),
            preserve_default=False,
        ),
    ]
