# Generated by Django 4.2.7 on 2023-12-27 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0004_title_verset'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='n_verset',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(286)]),
            preserve_default=False,
        ),
    ]
