# Generated by Django 4.2.7 on 2023-12-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0006_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
