# Generated by Django 4.2.7 on 2024-01-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0007_remove_band_like_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_jour', models.TimeField()),
                ('fajr', models.TimeField()),
                ('dhuhr', models.TimeField()),
                ('asr', models.TimeField()),
                ('maghreb', models.TimeField()),
                ('icha', models.TimeField()),
            ],
        ),
    ]
