# Generated by Django 4.2.7 on 2024-01-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0008_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date_jour',
            field=models.DateField(),
        ),
    ]
