# Generated by Django 4.2.7 on 2024-01-26 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0010_rename_title_sourate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Christ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('section', models.CharField(max_length=3000)),
                ('verset', models.CharField(max_length=5000)),
                ('n_verset', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1292)])),
            ],
        ),
        migrations.DeleteModel(
            name='Band',
        ),
    ]
