# Generated by Django 4.2.7 on 2024-01-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0012_date2'),
    ]

    operations = [
        migrations.AddField(
            model_name='date2',
            name='annee',
            field=models.IntegerField(default=2024),
        ),
    ]
