# Generated by Django 4.2.7 on 2024-01-28 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0014_juda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chabbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='date2',
            name='chavouot',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='date2',
            name='hanouka',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='date2',
            name='pessah',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='date2',
            name='pourim',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='date2',
            name='roch',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='date2',
            name='simhat',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='date2',
            name='souccot',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='date2',
            name='yom',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
