# Generated by Django 4.2.7 on 2024-01-29 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0015_chabbat_date2_chavouot_date2_hanouka_date2_pessah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chabbat',
            name='debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='chabbat',
            name='fin',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
