# Generated by Django 4.2.7 on 2024-01-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0016_chabbat_debut_chabbat_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chabbat',
            name='debut',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chabbat',
            name='fin',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
