# Generated by Django 4.2.7 on 2024-01-29 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0017_alter_chabbat_debut_alter_chabbat_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chabbat',
            name='debut',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chabbat',
            name='fin',
            field=models.DateTimeField(),
        ),
    ]
