# Generated by Django 4.2.7 on 2024-01-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0018_alter_chabbat_debut_alter_chabbat_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourate',
            name='n_verset',
            field=models.IntegerField(),
        ),
    ]
