# Generated by Django 4.2.7 on 2024-01-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0020_remove_christ_n_verset_christ_n_chap'),
    ]

    operations = [
        migrations.AddField(
            model_name='christ',
            name='n_verset',
            field=models.IntegerField(default=1),
        ),
    ]
