# Generated by Django 4.2.7 on 2024-01-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0021_christ_n_verset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juda',
            name='n_verset',
        ),
        migrations.AddField(
            model_name='juda',
            name='n_chap',
            field=models.IntegerField(default=1),
        ),
    ]
