# Generated by Django 4.2.4 on 2024-02-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0023_juda_n_verset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
