# Generated by Django 4.2.4 on 2024-02-05 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0024_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='raison',
            field=models.CharField(choices=[('question', 'Question'), ('commentaire', 'Commentaire'), ('probleme', 'Problème'), ('autre', 'Autre')], default='question', max_length=20),
        ),
    ]
