# Generated by Django 4.2.4 on 2024-02-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0025_contact_raison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='raison',
            field=models.CharField(choices=[('question', 'Question'), ('avis', 'Avis'), ('probleme', 'Problème'), ('autre', 'Autre')], default='question', max_length=20),
        ),
    ]
