# Generated by Django 4.2.4 on 2024-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0026_alter_contact_raison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='raison',
            field=models.CharField(blank=True, choices=[('question', 'Question'), ('avis', 'Avis'), ('probleme', 'Problème'), ('autre', 'Autre')], default='question', max_length=20),
        ),
    ]
