# Generated by Django 4.2.4 on 2024-02-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0027_alter_contact_message_alter_contact_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='contact',
            name='raison',
            field=models.CharField(choices=[('question', 'Question'), ('avis', 'Avis'), ('probleme', 'Problème'), ('autre', 'Autre')], default='question', max_length=20),
        ),
    ]
