# Generated by Django 5.0.2 on 2024-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0028_alter_contact_mail_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sourate_arabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('verset', models.CharField(max_length=5000)),
                ('n_verset', models.IntegerField()),
            ],
        ),
    ]
