# Generated by Django 5.0.2 on 2024-02-11 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourates', '0030_juda_hebreu'),
    ]

    operations = [
        migrations.AddField(
            model_name='date2',
            name='ramadan_debut',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='date2',
            name='ramadan_fin',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
